#!/bin/bash
_iquitnow(){
    set -Eeuo pipefail
    IFS=$'\n\t'

    if test "${1-none}" == "--no-dry-run"
    then
        _purge(){
            for ff in "$@"
            do
                rm -fvr "$ff" || true
            done
        }
    else
        _purge(){
            for ff in "$@"
            do
                find "$ff" -type f -ls || true
            done
        }
    fi

    _purge ~/.bash_history ~/.bash_logout ~/.cifscreds
    _purge ~/.netrc ~/.vscode ~/.viminfo
    _purge ~/.config/google-chrome

}
alias iquitnow=_iquitnow

